<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="106" started-at="2015-05-06T22:38:30Z" finished-at="2015-05-06T22:38:30Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="106" started-at="2015-05-06T22:38:30Z" finished-at="2015-05-06T22:38:30Z">
      <class name="log4j.ClassName">
        <test-method status="FAIL" signature="setUp()[pri:0, instance:log4j.ClassName@7a92922]" name="setUp" is-config="true" duration-ms="0" started-at="2015-05-06T17:38:30Z" finished-at="2015-05-06T17:38:30Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at log4j.ClassName.setUp(ClassName.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="testAbi()[pri:0, instance:log4j.ClassName@7a92922]" name="testAbi" duration-ms="16" started-at="2015-05-06T17:38:30Z" finished-at="2015-05-06T17:38:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAbi -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:log4j.ClassName@7a92922]" name="tearDown" is-config="true" duration-ms="0" started-at="2015-05-06T17:38:30Z" finished-at="2015-05-06T17:38:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- log4j.ClassName -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
